### PR TITLE
Add start position to Context

### PR DESCRIPTION
**Pull request by North101**
This is not necessarily finished. It works for what I need it to do but I've not verified if the start position is accurate. I've opened it to ask for opinions. It could be cleaner with some other changes but I wanted to keep it backwards compatible for now.

I've used this change and some modifications to the [query](https://github.com/isoos/query) package to be able to figure out the context of the current cursor position and offer suggestions.

### CODE REVIEW

**Comment by renggli** [comment]
Can you explain the purpose of this? 

To be considered for merging into the main branch, this would also need a detailled evaluation of performance impact.

**Comment by North101** [comment]
I'm using petitparser as a search text parser. It works great for that, but I also want to offer suggestions based on where the cursor position and what is at the cursor position. In order to offer suggestions I need to know the bounds of each result.

I can't see this having any performance impact. All it does is copy the previous context's `position` to the result's `start`.

**Comment by North101** [comment]
Well... I completely missed that `.token()` had a start and end to it. thanks

**Comment by renggli** [comment]
No worries, great that this works for you. Let me know if the documentation could somehow be improved?

**Pull request closed without merging**
