### PR TITLE
Use for-in instead of indexed loop

### PR DESCRIPTION
**Pull request by f3ath**
I think this would be a bit more idiomatic. Not sure about performance implications though.

### CODE REVIEW

**Comment by renggli** [comment]
At least on the command line this does no longer seem to have a measurable performance impact (there used to be a large one in the past):

benchmark

**Comment by renggli** [comment]
Some other slowdowns visible in more complicated parsers:

examples

**Comment by gmpassos** [comment]
It's extra object allocation (the Iterator). It will "visible" when the test has enough time to show some work and there's a lot of objects to collect.

**Comment by f3ath** [comment]
Closing due to unwanted performance implications.

**Pull request closed without merging**
